#!/bin/sh -f
#
# A simple script to build robot controllers that make use of the
# libplayerc++ library.

# Added Robot.cc. Remove later if needed
g++ -o $1 `pkg-config --cflags playerc++` $1.cc Robot.cc `pkg-config --libs playerc++`
